version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - CORS_ORIGINS=http://localhost:${FRONTEND_PORT:-3000},http://127.0.0.1:${FRONTEND_PORT:-3000}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    command: python app.py

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT:-5000}
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT:-5000}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    depends_on:
      - backend
    restart: unless-stopped
    command: npm start
