# NCAA API base URL
NCAA_API_BASE_URL = "https://ncaa-api.henrygd.me"

# Stat category mappings
STAT_CATEGORIES = {
    21: "Total Offense",
    22: "Total Defense", 
    23: "Rushing Offense",
    24: "Rushing Defense",
    25: "Passing Offense",
    27: "Scoring Offense",
    28: "Scoring Defense",
    29: "Turnover Margin",
    40: "Team Passing Efficiency Defense",
    96: "Kickoff Returns",
    97: "Punt Returns",
    98: "Net Punting",
    456: "Fumbles Recovered",
    457: "Passes Intercepted",
    458: "Fumbles Lost",
    459: "Passes Had Intercepted",
    460: "Turnovers Gained",
    461: "Turnovers Lost",
    462: "Punt Return Defense",
    463: "Kickoff Return Defense",
    465: "Team Passing Efficiency",
    466: "Team Sacks",
    467: "Team Tackles For Loss",
    468: "Sacks Allowed",
    693: "First Downs Offense",
    694: "First Downs Defense",
    695: "Passing Yards Allowed",
    696: "Tackles For Loss Allowed",
    697: "Fewest Penalties Per Game",
    698: "Fewest Penalty Yards Per Game",
    699: "3rd Down Conversion Pct",
    700: "4th Down Conversion Pct",
    701: "3rd Down Conversion Pct Defense",
    702: "4th Down Conversion Pct Defense",
    703: "Red Zone Offense",
    704: "Red Zone Defense",
    705: "Time Of Possession",
    741: "Passing Yards Per Completion",
    742: "Winnning Percentage",
    756: "Completion Percentage",
    785: "Blocked Kicks",
    786: "Blocked Kicks Allowed",
    790: "Blocked Punts",
    791: "Blocked Punts Allowed",
    876: "Fewest Penalties",
    877: "Fewest Penalty Yards",
    926: "Defensive TDs",
}
